version: '2'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "3001:3001"
    links:
      - "db:db"

  db:
    image: mongo:latest
    container_name: "mongodbskeleton"
    #environment:
    #  - MONGO_DATA_DIR=/data/db
    #  - MONGO_LOG_DIR=/dev/null
    #  - MONGODB_USER=mongodb
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    #command: mongod --smallfiles --logpath=/dev/null # --quiet
